### ISSUE TITLE
Cannot set a Minecraft Team as the display and hidefrom

### ISSUE THREAD

**Issue by AcornGR** [Xezard/XGlow#13]
When i try to use the command it throws an error, on the line that i set the hidefrom and display
i have this set for the teams
```java    Glow glow = Glow.builder().animatedColor(ChatColor.RED).name("test").build();
    ScoreboardManager manager = Bukkit.getScoreboardManager();
    Scoreboard board = manager.getMainScoreboard();
    Team RedTeam = board.getTeam("Red");
    String RedPlayers = String.valueOf(RedTeam.getEntries());
    Team BlueTeam = board.getTeam("Blue");
    String BluePlayers = String.valueOf(BlueTeam.getEntries());
```
I have made it a string but have tried both making it a player, a set (which it normally is i think) and an entity and it still doesn't work

this is what i have for the glow effect
```java    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        glow.addHolders((Entity) sender);
        glow.hideFrom(UUID.fromString(BluePlayers));
        glow.display(UUID.fromString(RedPlayers));
```

**Comment by Xezard** [comment]
Hello. Please, show your error stacktrace.

**Comment by AcornGR** [comment]
Hi, here is the error stacktrace: https://pastebin.com/59viJCbD
and here is the entire server log: https://pastebin.com/cCn9MbJT

**Comment by Xezard** [comment]
```java
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: [_Steluba, DeathInnit, DeqthStreeks]
```

This is not a plugin bug. If you want to hide the glow from certain players, just call the required method: https://github.com/Xezard/XGlow/blob/master/api/src/main/java/ru/xezard/glow/data/players/IPlayerViewable.java
