### ISSUE TITLE
glowing entity by entity id

### ISSUE THREAD

**Issue by pukpukpuk** [Xezard/XGlow#18]
adding entity id in glow holders

**Comment by Xezard** [comment]
You can get entity by id and then get glow by entity from GlowsManager.

**Comment by pukpukpuk** [comment]
what about npcs? they are fake entities

**Comment by Xezard** [comment]
I will add support in the update.

**Comment by Xezard** [comment]
Everything would be simple if i didn't have to edit the entity metadata in order to turn on the glow of the entity.
Perhaps I'll consider implementing this feature. But, I think, it will be easier to fasten the public API for GlowProcessor.
