### ISSUE TITLE
Legacy plugin XGlow v1.0.7 does not specify an api-version.

### ISSUE THREAD

**Issue by Dymeth** [Xezard/XGlow#20]
Server startup warning: `Legacy plugin XGlow v1.0.7 does not specify an api-version.`
I suggest specifying `api-version: 1.13` to hide this

**Comment by Xezard** [comment]
Fixed in https://github.com/Xezard/XGlow/commit/bc7b2180d38ecc4c751365185da9e9492f80ec63.
