### ISSUE TITLE
Maven cannot find XGlow. (IntelliJ)

### ISSUE THREAD

**Issue by CrazySqueak** [Xezard/XGlow#23]
Error Message:
```
ru.xezard:XGlow:pom:${revision} was not found
```

My pom.xml (relevant parts only):
```
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        
        <dependency>
            <groupId>com.github.Xezard</groupId>
            <artifactId>XGlow</artifactId>
            <version>1.0.9</version>
        </dependency>
```

**Comment by Xezard** [comment]
Try like this:
https://jitpack.io/#Xezard/XGlow/1.0.9

```xml
<dependency>
  <groupId>com.github.Xezard.XGlow</groupId>
  <artifactId>XGlow</artifactId>
  <version>1.0.9</version>
</dependency>
```

**Comment by Gabo6480** [comment]
> Try like this: https://jitpack.io/#Xezard/XGlow/1.0.9
> 
> ```
> <dependency>
>   <groupId>com.github.Xezard.XGlow</groupId>
>   <artifactId>XGlow</artifactId>
>   <version>1.0.9</version>
> </dependency>
> ```

`Cannot resolve com.github.Xezard.XGlow:XGlow:1.0.9`

**Comment by Gabo6480** [comment]
The last version that works for me is 1.0.7

**Comment by ItWasEnder** [comment]
I am unable to get any version of XGlow to work using jitpack. I have had this issue for a while and I've tried everything I can think of to solve this.
