### ISSUE TITLE
Cannot add dependency to MAVEN.

### ISSUE THREAD

**Issue by MochidsukiC** [Xezard/XGlow#28]
Even if I fill in the dependencies in pom.xml, I get an error and cannot use them.

Here is my current code.

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.19.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>4.8.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Xezard.XGlow</groupId>
            <artifactId>XGlow</artifactId>
            <version>1.1.0</version>
        </dependency>
    </dependencies>

**Comment by Xezard** [comment]
```
<dependency>
    <groupId>ru.xezard</groupId>
    <artifactId>XGlowAPI</artifactId>
    <version>1.1.0</version>
</dependency>
```
