### ISSUE TITLE
Wiki Entry is outdated/incorrect

### ISSUE THREAD

**Issue by Braekpo1nt** [Xezard/XGlow#34]
The [Installation]() page on the wiki says that to include the API as a dependency, you must add `implementation 'ru.xezard:XGlowAPI:{latest_version}'` to your `build.gradle`. However, the actual dependency string should be `implementation 'com.github.Xezard.XGlow:XGlowAPI:{latest_version}'`, according to `jitpack`.

**Comment by Xezard** [comment]
Hi. Thanks a lot for the fix! Corrected the description in the wiki.
